### PR TITLE
PR-2

### PR DESCRIPTION
**Pull request by tomwang2011**
Datashaper breaks as it is looking for stopwords file

### CODE REVIEW

**Comment by iandreariley** [comment]
Hey Tom, we gotta try to filter some stopwords. Do you have the stopwords file in the right directory?

**Comment by iandreariley** [comment]
Looks like I didn't have it added to the project. Try pulling now. Should be located in the base directory of the project.

**Comment by tomwang2011** [comment]
Oh I thought we are not going to use it since on the readme you put "-Reasoning for not using a stopword filter". No need to have this if we are still planning on using stopwords, i'll just add a blank document in it's place.

**Comment by tomwang2011** [comment]
okay i'll rebase to it

**Comment by iandreariley** [comment]
Oh I see what you're saying. Yeah. I read about that but then decided against it since the seed paper did remove stopwords.

**Pull request closed without merging**
